/**
 * The Chinese characters and Korean syllables in everyday use, for the
 * check in resetTokenStrength.js that refuses a reset token whose hex is
 * text written as UTF-16.
 *
 * SECURITY (2026-10-05, A2): round 5 of the verification. Chinese and
 * Korean take up half of the 16-bit range, so that check could only count
 * them all as text at the cost of refusing random tokens all the time, and
 * counted none: [Convert]::ToHexString([Text.Encoding]::Unicode.GetBytes(
 * "重置密码面板令牌")) passed. The ones people write are a small part of
 * them, listed in the national character sets' first levels:
 *   - GB 2312 level 1, simplified Chinese: 3,755 characters (GB2312 B0A1-D7F9);
 *   - Big5 level 1, traditional Chinese: 5,401 (Big5 A440-C67E);
 *   - JIS X 0208 level 1, Japanese kanji: 2,965 (EUC-JP B0A1-CFD3);
 *   - KS X 1001, Korean syllables: 2,350 (EUC-KR B0A1-C8FE);
 * 9,524 code points in all, many of them shared, 14.5% of the 16-bit range.
 * Each is one bit below, from U+4E00 to U+D7A3, in base64. They were read
 * with the WHATWG decoders of a Node built with full ICU;
 * resetTokenStrength.test.js reads them again and compares. The panel's
 * packaged builds can't: their Node has no legacy-encoding decoders, which
 * is why the bits are written out here.
 */

const FIRST = 0x4e00;
const LAST = 0xd7a3;

const BITS = [
  "i297//YsFW8o+93jQwILQEXbNt/2ewyE++z6wzhUzagC7qPnUYRRNcjhu34JkincWKnCKOvj4IAcxIPlC+IqRUG6Vod6L0BW",
  "iNIgFCCg9KQhIUIHDLGsSKDgYgSgYioKNQM1gQIEjJn7e7cUpHv7O2E3pho1lf0oUboCONOkS6/LRcYvMU/BL458Uzi4hrWg",
  "jCcK6AsfHsqqCqTr3AAtzWeh4SILhALOq8f+VdfIu4t0GiClZCMMiA5/0ot//+8bWv+v6MH7eltNRyMZBAXqOVHYZQbAnw6p",
  "12OCgGJnBDTSglEAkNCKQVqE6NB6RABZnQ4Qt4BczwjgQgqUeoHAYEFj0YkAwleKBFCICjSfUgehwCEALEHQEAcXAmwdLB/k",
  "WKtMgYizCUyF5IPsU4aAEBwIDAhNSAAADEgQkBEAkBZlBiIgE4QzBAMclkcEKiBiKQSM0kBDCECiVCrDFNrPJpCicJa17pJH",
  "kMvzBaVnWCPeJUxiONEISmAuHxVoHUCImhIKmSmCQhBDBgAERATQgAAABAyAAAxwBhLAAUoCIAgAGwAgFBQRAQkAu79YDiul",
  "qrug/39MeeP0EA3o9lth39bvUiWUMIL/Z+8jcTeRAoIGEJMIAjuKgQAABAJDpVEowkDSCpQiEACAEAEAAIIAAJAIECAAAAA1",
  "ADJUYO5LnmhuEWO94OjJIS0QsIgOCFz72oT51sEo4EEeB0ikDRDI3B+NvYnhoqJWQFWsInQ+g5qzH49TA1e4ImgwwDOBDCKp",
  "B8B0OKOPIAhIKCUCPL9pkDAyUIRJl3Q54AwilcvrWw5D4yScmACQwJB5IqWMSeFQBEwTBJBbRECELwUASADk1QH1Z41GxN3J",
  "g2s+Ccj6S9JRBu5dNxkisvR73b/v89rwhkNC7juNAORk8qHQjkvGDJ2TRQuvF5wNSaJFDApmECZnoNlQADRQZNQFFoGAogAP",
  "rAEvRjR6Ldq2bBRFRTCXTEGAFDMYnEDLIJPya0wQtQGMWqOasrqBMiLYwADlM8IExdQ4gLGhAlAumixkUMPRRJYjwiFESRID",
  "0AJAMkESnfMJK7CowP0yJE3Cy9Anpa/QkgqpNA2M0QEShB93JZI6yLyJygEGBpAzbxEbsKgDQIBuAJigxqFrEBEqpIWJQCYO",
  "IWgEGgAgEaAABDhsDemoMkREMBhIaZAICjgJCwAhCCgmDIrCCg4iJ5AJAIMGCALAEUCREA3QCAkMAAgsIBEADBAEQSCPAARk",
  "gFIJkv6GnJtIDkABEMC0nGPo/A8CmAAgIIHbiNzZmUGHYqHuEwVVZm6zXYv2XAr7MhboWC+FKzgCWIRIoE5me/JMChZgVpAD",
  "pFc4utrHJJHxGEZHUl2qDqAvmS57shRFGGRQiYjCBMApEkExpIxQFLYYOmRyk5TARoI4AA2eDsEgIBLZUeABFVFBgBDTAFoC",
  "DwAkiRPaA0RAiiLtwBEFQAAQAkEYqGHxAEY0AhD4CDcOhQCL0LqAIgAGMBZCAEEQQFJAUvBTACAQhBSCABECQhhDJZLhcBBZ",
  "QCABCAA142/AEUSrh4I0JhMERAiFkEACFUGBSgNygzMAQEiaIE7QwDBAgQAIIaUN0QpAiCCLjQgFJAFAAWQAQGgmAQhkhXiU",
  "AgAg3hmmSUAJCADRyAMBoACEUBRdQMAAEDAilWw7ry0g2BI2ZQzZgcDMgqY+yCxzpCc0Sw0GH4YDKgiA1w4QBUQQRIEuUgZ9",
  "1ElLBABAE4Rs5dfZusQUU4IaAIABg8BVA4AAWG4dAKKwWAbAoTYJuIAAiBys6gjgBjB0pOEglcUpQCQgANiEkIJyqoGIAhtU",
  "IgwhBICRkAQCQAACQBwAVMMD4eQlIYCFMuAAAMBEC+5LKwaB2IIBKSFpkNQBQI64RfiBAA8K0IYaIe6xIcYAhLgMQNIppECm",
  "QAkSSmFRABZAq1cIgUCgQtGosCADJhIB0xIIClNigkCAMAJAigyA4QkwAYA5UAxoBiqkibBEKmIARGDyhYABSfUusR+H2A8W",
  "XRAhSEZBbwICgApWBTA37YCMBmcJkxQKEgcDaEjItuJqLTRGAi4JMgSQWBDVnO6n+OUu9+wmubFxQnglAUNQJRARs4QETqUC",
  "IF0QRBKDRLMiUDSBA0oLGns4pxNABUipRBxURQKE3+D4GkgtN84WxFtQQHwyoFs15IdLBBiKC0NAXDsAYEgbzwWFAD0BAwjk",
  "TaIIhaw1GFzld5XZBB3jAoAIAANAwM9EBCgEsmiwi2ugoJ7Y6IgCAn5CgBCAGXYDSYYVBZqIgBlARkxBhQiGIqKUWJABghch",
  "mHwAILATIjFAQoAISjqiBAQIEVIAAASRUQ5KoABQAIBBAJoEajigMAhHgEIAJxBAkASSGkDfAQYCoiEgMAaADsAMggQAIACB",
  "AMAz3IAIAm4HFCgQGIZiANFuEcoQYAFLzQWsESYCkIiAWqgCQQFQgQwgAMAECAgMQQkGAAGQBEogIDCADgBCCmEwmCouGYGi",
  "FilEUAAokgAmhDSzEoEYY4QELQQiDEQpEABAwBGUBIDKiMgUwBQMJHcDFABIABARDdXrqSwkWlxCAHNITXsPGqA2KkX7NUWS",
  "lLpEGMBoylUXRIEqAxkAAkLCAJdAmJUgCQRNFD7rTfdzN6Js7ri2bWptiRRcM5OAQlcxBAY8CAYENghgh5/dub9FDlhfNBA9",
  "IK3I6P7/s9ce3FFN3yj5ACIMIIIIARhESFgCrFKFKBQAlAHgBg4yAhQPIIJYMFSUpi4KAAKcBAQBvBSIBAAAeQgGPPhghgjJ",
  "NGIQgMLTEahoB+vaSOsH/vZBE/t0L5Enb6b97g1AZlmm7Lt7L2O0tZ+NKwBMxGILCkQCIIYhsGEEAoRDgCATAgB/lGQsVvKB",
  "iCqFXBhYEgXj/4MzyCIgAIBiM0AIAJDjMSqCDFQAElkpAEoVADGMGKIABAAQJA0RUAAhB0fZTAAALBAMIBAhQAQU0AWEUAkA",
  "CCHCsRYBACAIAAADAEgsBRAADgAZBIXwAEMM4udDKkhvAAAwCjBHRTMZgwZ64QEKgyQDEAggwYANyh4BPiMGCMAdcREG5ZUv",
  "J0ITkAJUfoj1OSFpPhf9JXDtMRuJBdJb875mWgyPxUrR5kpQkAQFYxQBRFpHI1gQMKgAAUkgAABKGggQwGJoim4VjxUSOJEb",
  "QPA4SaCI4+72BcsxkYFKFBBAAMmEphRwKBYNTQJBIOAgAqZQIOBnlGKJRAIgcRoAcgEnqgQgAoACQEwCAAmhQCkgoIwk9Fta",
  "1JiCBBKBgRESgF4BQuQACEggAASsAQYQNuASBQCAgAAAQAYAAGwAAAEHQAiAASAgACAJACCgAkoAA9SAAACAEQIgABAQAAAB",
  "CABAQCACWADIQiQISBkAiAAAAjADFAQAAIIAAACAEAEEAIgAIAAEBgAAAMxqoCigKIQAABAAIbMECIygYAIw3hjwFnsBgZAA",
  "gEAoAgGQEEgADAWQzhSEgBAoEZYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACTB/8+EbADEwEoEBEAAJMF",
  "ex4RsAOXATsSEaAAk5VrMFGwAhEBMjARsAIRAQowebgGEwEwEACAABMBCxARAACTAysQAAAAkwVrdFGwIxMBOzAQAAAAAABw",
  "EbADEwApEBGAIQEAADAVsA4DATAwAAACEQEjEAAAABOBaxAQAAMTARMQETAAAQAAMFW4IgAAADARsAKXB/s6EbADEwEhAAAA",
  "ABsNOzgRsAMTATMRAQAAEwUrHBEAAQAAABARsAATASowGbACAQAQEAAAABEBAzAQMAITB2sUEQAAEwUrdPm4jxMBOxAAAAAA",
  "AABw2bBKEwE7EBEAAxEAADBZsSoRAQAQAAABEQELEAAAABMBKxAAAAEBACAQEaACEQEhMFmwAgEAADAZsAcTATs4EbADAAAA",
  "AAAAABMNOzgRsAMBABAAAAAAEwEgEBAAAAEAABABAAAAAAAwERgCAAAAEAAAABEBIwAAAACTAQsQETAAEQErMBGwxxMBOzAB",
  "gAIAAAAwEbCDEwErMBGwAxEACjARsAIRACAAAAABEQErEBGgAhMBKxAAAAEBAAAwEZACEwErMBGwZgAAADARsALTB2s6EbAH",
  "AwEgAAAAABMFazgRsAMTAbgQAAAAGwUrEAEAAwAAABARoAIRAQpwebCiEQEKEAAAABEBABARkAARAQkAAAAAkwW78vmwIhMB",
  "OzIBIAAAAAAwWbAGkwE7MBGgIxEAAHARsAIRABAQAAABEwEDEAEAAJMHKxYQAAEBAAAwEQACEQEpMBGwAAAAADBRsA4TBTs4",
  "EbADAwABAAAAAJMBORAAAAIDADsAAAAAEwEjAAAAAAAAABAAAAABACAwEZACAAAAAAAAAAAAABAAAAIRAQMAAAAAEwErsHmw",
  "IxMBOzARsAIRASHw2bBDEwE7MBGwAxEBIHBRsCITASAQEZABEQELMBGwApMBqxYAAAETASEwEbACAwEpMDGwAgAAADAZuEIb",
  "ATM4ETADAAAgAAAAABMFMxARAAAAAAAAAQAAkwUjMAEAAQEAEBARMAABAAAwETACAQAQEAAAABEAAAAAAAIThQMQERAAEwEr",
  "MHe4YxMBOzCRsKIRAQIwe/BXEwErcNHw4xEBGzBxuQoTATswAZACEwErMBGwAhMHKzARMAMTASMwEbACEwGrMBG0/hEBCTBx",
  "uEfTBXswEbADUwEhEBEAABMFazARsAIRATMQAAAAEwXrOBCgAgEAMBARsAITACAwcbACAQAQEAAAABMBCxAREAATASsAAAAA",
  "kwVrNpWwAxMBOxABAAIAAAAwEbADAQAgEAAAAQAAADARsAoDARAQAAABEQEDAAAAAhMBIxAAAAMAAAAQAAAAAQAAEACQAgAA",
  "ADARMIZTAXswEbADUQEhAAAAABMBOzARsAIRABAQAQACEwErEBEAAgAAABARsAIBAAEwEbACAQAQEAEAABEBKxAREAITASsA",
  "AAAAkwMrMBGwAhMBOzAAAAIAAAAwGbADEwErEBGwAwEAADARsAITASEQAAACAQEAEAAAABMBKxARAAIBACAwEbACEQEBMBEw",
  "AgAAADARsAITAzswEbADAQAgAAAAABMFOzARsAIRABAQAQAAEwErFAEAAAEAABABgAIBAAAwEbACAQAQEAAAABMBIxAREAKT",
  "BQsQETAAEwErcFGwIxMBOzAAAAAAAAAwEbADEwErEBEwAwEBCjARsAIBACAAAAAAEQAAEBGgAJMFKxAAAAIAAAAQEZAAEQEp",
  "EBGwAAAAADARsAITISswEbADAQAgAAAAABMFKzARsAITATsQESAAEyErMhGAAhMAKDARoAIRAQowEZICEQEhMBEAAhMBKzAR",
  "kALTAysSETACEwErAA==",
].join("");

let table = null;

export const COMMON_CJK_FIRST = FIRST;
export const COMMON_CJK_LAST = LAST;

export function isCommonCjkChar(unit) {
  if (unit < FIRST || unit > LAST) return false;
  table ??= Buffer.from(BITS, "base64");
  const offset = unit - FIRST;
  return (table[offset >> 3] & (1 << (offset & 7))) !== 0;
}
